create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  index integer not null,
  content text not null,
  answer text not null,
  category text,
  lang varchar(2) not null default 'en',
  on_site boolean not null default false,
  display boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.technologies (
  id bigint generated by default as identity primary key,
  label text not null,
  description text,
  href text not null,
  src text not null,
  category text,
  display boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists questions_index_idx on public.questions (index);
create index if not exists technologies_category_idx on public.technologies (category);

alter table public.questions enable row level security;
alter table public.technologies enable row level security;

drop policy if exists "questions_authenticated_read" on public.questions;
create policy "questions_authenticated_read" on public.questions for select to authenticated using (true);
drop policy if exists "technologies_authenticated_read" on public.technologies;
create policy "technologies_authenticated_read" on public.technologies for select to authenticated using (true);
