<?php

return [
    [
        'label' => 'PHP',
        'description' => 'Popular server-side programming language, often used for creating dynamic websites and web applications.',
        'href' => 'https://www.php.net/',
        'src' => 'php.svg',
    ],
    [
        'label' => 'Laravel',
        'description' => 'A PHP open-source framework designed for simple web application development with elegant and readable code.',
        'href' => 'https://laravel.com/',
        'src' => 'laravel.svg',
    ],
    [
        'label' => 'TypeScript',
        'description' => 'A superset of JavaScript that adds static typing, which helps detect errors and improves code readability',
        'href' => 'https://www.typescriptlang.org/',
        'src' => 'typescript.svg',
    ],
    [
        'label' => 'Nuxt',
        'description' => 'It provides a number of features that make it easy to build fast, SEO-friendly, and scalable web applications.',
        'href' => 'https://nuxt.com/',
        'src' => 'nuxt.svg',
    ],
    [
        'label' => 'Vue',
        'description' => 'A progressive JavaScript framework for building user interfaces, known for its simplicity and performance.',
        'href' => 'https://vuejs.org/',
        'src' => 'vue.svg',
    ],
    [
        'label' => 'PrimeVue',
        'description' => 'A UI component library for the Vue framework, offering a rich selection of ready-made user interface elements',
        'href' => 'https://primevue.org/',
        'src' => 'primevue.svg',
    ],
    [
        'label' => 'GSAP',
        'description' => 'A JavaScript library for creating high-performance animations, easing, and transitions.',
        'href' => 'https://greensock.com/gsap/',
        'src' => 'gsap.svg',
    ],
    [
        'label' => 'Chart.js',
        'description' => 'Simple yet flexible JavaScript charting library for the modern web',
        'href' => 'https://www.chartjs.org/',
        'src' => 'chart-js.svg',
    ],
    [
        'label' => 'HTML5',
        'description' => 'The latest version of the HTML markup language. It enables the creation of responsive and semantic websites with multimedia support, without the need for additional plugins.',
        'href' => 'https://html.spec.whatwg.org/multipage/',
        'src' => 'html5.svg',
    ],
    [
        'label' => 'SCSS (Sass)',
        'description' => 'A CSS preprocessor that extends its capabilities by adding variables, nesting rules, and other advanced features.',
        'href' => 'https://sass-lang.com/',
        'src' => 'scss.svg',
    ],
    [
        'label' => 'MySQL',
        'description' => 'A relational database, popular in web applications. It enables the storage and management of large sets of data',
        'href' => 'https://www.mysql.com/',
        'src' => 'mysql.svg',
    ],
    [
        'label' => 'Docker',
        'description' => 'A platform for containerizing applications, enabling the execution of apps in isolated environments. It simplifies the creation, deployment, and management of applications.',
        'href' => 'https://www.docker.com/',
        'src' => 'docker.svg',
    ],
    [
        'label' => 'Heroku',
        'description' => 'A cloud-based PaaS (Platform-as-a-Service) platform, allowing easy deployment, scaling, and management of web applications',
        'href' => 'https://www.heroku.com/',
        'src' => 'heroku.svg',
    ],
    [
        'label' => 'Vitest',
        'description' => 'A lightweight and fast testing framework for applications written in TypeScript and JavaScript, designed to work as a companion to Vite.',
        'href' => 'https://vitest.dev/',
        'src' => 'vitest.svg',
    ],
    [
        'label' => 'Pest',
        'description' => 'A simple and elegant unit testing framework for PHP, designed with readability and performance in mind.',
        'href' => 'https://pestphp.com/',
        'src' => 'pest.svg',
    ],
    [
        'label' => 'Storybook',
        'description' => 'A tool for building, testing, and documenting user interface components in isolation, supporting various frontend frameworks.',
        'href' => 'https://storybook.js.org/',
        'src' => 'storybook.svg',
    ],
    [
        'label' => 'Cypress',
        'description' => 'An end-to-end testing framework for web applications. It allows fast and easy writing of user interface tests in real browsers.',
        'href' => 'https://www.cypress.io/',
        'src' => 'cypress.svg',
    ],
    [
        'label' => 'Sonarcloud',
        'description' => 'A cloud-based tool for code quality analysis. It helps identify bugs, security issues, and technical debt.',
        'href' => 'https://www.sonarsource.com/products/sonarcloud/',
        'src' => 'sonarcloud.svg',
    ],
    [
        'label' => 'Biome',
        'description' => 'A fast, modern, and powerful linter and formatter for JavaScript, TypeScript, and CSS.',
        'href' => 'https://biomejs.dev/',
        'src' => 'biome.svg',
    ],
    [
        'label' => 'Stylelint',
        'description' => 'A linter for CSS and SCSS, helping enforce styling standards and detect errors in code.',
        'href' => 'https://stylelint.io/',
        'src' => 'stylelint.svg',
    ],
    [
        'label' => 'Husky',
        'description' => 'A tool for managing Git hooks, enabling the execution of scripts (e.g., linting) before committing changes to a repository.',
        'href' => 'https://typicode.github.io/husky/',
        'src' => 'husky.svg',
    ],
];
